version: "3.7"
services:
  app:
    build:
      context: ./sample-apps/spring-boot
    depends_on:
      - otel
    environment:
      - INSTANCE_ID
      - LISTEN_ADDRESS=0.0.0.0:8080
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - OTEL_RESOURCE_ATTRIBUTES=service.name=adot-integ-test
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
      - XRAY_ENDPOINT=http://otel:2000
      - OTEL_JAVAAGENT_DEBUG=true
      - OTEL_METRICS_EXPORTER=otlp
    volumes:
      - /tmp/awscreds:/tmp/awscreds
    ports:
      - '8080:8080'

