{{- if .Values.fluentbit.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.fluentbit.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.fluentbit.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.fluentbit.name }}
    namespace: {{ include "aws-for-fluent-bit.namespace" . }}
{{- end }}
