version: "3.7"
services:
  otel:
    image: amazon/aws-otel-collector:latest
    command: --config /config/collector-config-local.yml
    volumes:
      - ~/.aws:/root/.aws:ro
      - .:/config
    environment:
      - AWS_REGION=us-west-2
    ports:
      - '4317:4317'

  app:
    image: aspnetapp:latest
    environment: 
      - AWS_REGION=us-west-2
      - INSTANCE_ID
      - LISTEN_ADDRESS=0.0.0.0:8080
      - OTEL_RESOURCE_ATTRIBUTES=service.name=aws-otel-integ-test
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - '8080:8080'     
    volumes:
      - ~/.aws:/root/.aws:ro
