/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.1.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

val otelVersion = "1.17.0"

repositories {
    mavenCentral()
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    // OpenTelemetry APIs and SDKs
    implementation(platform("io.opentelemetry:opentelemetry-bom:${otelVersion}"))
    implementation("io.opentelemetry:opentelemetry-api")
    implementation("io.opentelemetry:opentelemetry-sdk")

    // OpenTelemetry Exporters
    implementation("io.opentelemetry:opentelemetry-exporter-otlp")

    // OpenTelemetry Aws Xray dependencies
    implementation("io.opentelemetry:opentelemetry-extension-aws")
    implementation("io.opentelemetry:opentelemetry-sdk-extension-aws")
    implementation("io.opentelemetry.contrib:opentelemetry-aws-xray:${otelVersion}")

    // OpenTelemetry AWS SDK Library Instrumentation
    implementation(platform("io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:${otelVersion}-alpha"))
    implementation("io.opentelemetry.instrumentation:opentelemetry-aws-sdk-2.2")

    // Opentelemetry OkHttp Library Instrumentation
    implementation("io.opentelemetry.instrumentation:opentelemetry-okhttp-3.0:${otelVersion}-alpha")

    implementation(project(":base"))
}


application {
    // Define the main class for the application.
    mainClass.set("software.amazon.adot.sampleapp.MainManual")
}
