# Service account provides identity information for a user to be able to authenticate processes running in a pod.
{{- if .Values.adotCollector.daemonSet.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.adotCollector.daemonSet.serviceAccount.name }}
  namespace: {{ include "adotCollector.daemonSet.namespace" . }}
{{- end }}
