# Service account for ADOT Collector as a DaemonSet specifies an identity for processes in pod for authentication.
{{- if .Values.adotCollector.daemonSet.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.adotCollector.daemonSet.serviceAccount.name }}
  namespace: {{ include "adotCollector.daemonSet.namespace" . }}
{{- end }}
